### ISSUE TITLE
SMFramework issue on MacOS Catalina

### ISSUE THREAD

**Issue by elbracht** [ellunium/sketch-measure-latest#10]
Hello @ellunium,

thank you for this Fork. It is very helpful to continue using Sketch Measure with the new Sketch versions.

Unfortunately I get the following error since the update to Catalina:

```
“SMFramework” cannot be opened because the developer cannot be verified.
```

![Screenshot 2019-10-10 at 11 04 40](https://user-images.githubusercontent.com/2912000/66554743-d16b7380-eb4d-11e9-9135-1c799aeb7fc2.png)

**Comment by alexandwich** [comment]
Hi, elbracht,
Try this.It works for me.

**Run this in your terminal:**
`sudo xattr -r -d com.apple.quarantine /Users/${USER}/Library/Application\ Support/com.bohemiancoding.sketch3/Plugins/Sketch\ Measure.sketchplugin/Contents/Sketch/SMFramework.framework/SMFramework`

**Comment by elbracht** [comment]
@alexandwich Thanks for the fast reply. It works great.

**Comment by matt-bailey** [comment]
@alexandwich I was having a similar issue with a different plugin/resource and your answer pointed me in the right direction (I'd completely forgotten about `xattr`). Thanks 👍
