### ISSUE TITLE
Update to work with Sketch 63.1 (Mac OS Catalina)

### ISSUE THREAD

**Issue by janedepgen** [ellunium/sketch-measure-latest#13]
thanks for always working to keep this plugin up to date @ellunium ! any chance you can post a fix for the latest version of Sketch/the new Mac OS? (not sure which of those updates caused the plugin to break for me) thank you so much!!

**Comment by ellunium** [comment]
@janedepgen I’ll take a look soon, I need to upgrade to Catalina first.

**Comment by ellunium** [comment]
@janedepgen I just tested this fork (2.8.0) and it works well with Catalina and Sketch 63.1

https://github.com/ellunium/sketch-measure-latest/archive/master.zip

Maybe follow this: 

https://github.com/ellunium/sketch-measure-latest#still-not-working

Let me know how it goes.

**Comment by janedepgen** [comment]
thanks @ellunium ! I ended up getting an alert that the "SMframework could not be opened because the developer could not be verified" - I found a workaround for this (https://github.com/hashicorp/terraform/issues/23033) and now everything seems to be working ! 

the rest of my team also relies on this plugin and I was wondering if there was any way to avoid this error? is there a reason this can't be verified?

**Comment by ellunium** [comment]
That's the only way I'm afraid. :( 

As you can see in the link you shared, the new version of MacOS is stricter about running software that isn't signed with an Apple developer key. MacOS Catalina is requiring participation in Apple's developer program specifically, and the `SMframework` is currently not built to support that.

`SMframework` is created by @utom and it uses a compiled codebase done in XCode that I don't have access to make changes or make it compatible with Apple's requirement. 

Maybe one day :)

**Comment by ellunium** [comment]
Just leaving this if anyone needs it: 
https://github.com/ellunium/sketch-measure-latest/issues/10#issuecomment-540477016

**Run this in your terminal:**
`sudo xattr -r -d com.apple.quarantine /Users/${USER}/Library/Application\ Support/com.bohemiancoding.sketch3/Plugins/Sketch\ Measure.sketchplugin/Contents/Sketch/SMFramework.framework/SMFramework`

_Originally posted by @alexandwich in https://github.com/ellunium/sketch-measure-latest/issues/10#issuecomment-540477016_

**Comment by RobertoDeJesus1** [comment]
I am having the same issue. 
ellunium, could you please provide step by step on how to run it in the terminal?
