### ISSUE TITLE
Feature Request: Smart Layout for Properties

### ISSUE THREAD

**Issue by JordanTranchina** [ellunium/sketch-measure-latest#15]
It would be great to have property labels resize based on text size. I'm currently using the properties feature to take notes for my developers and would love to see these resize as I type. Is this possible to integrate with Sketch's Smart Layout feature?

**Comment by JordanTranchina** [comment]
https://www.sketch.com/features/smart-layout

**Comment by ellunium** [comment]
Hi @JordanTranchina, 
I will not be adding any more features to this fork, sorry.
