### ISSUE TITLE
Spec export doesn't work for Sketch v69

### ISSUE THREAD

**Issue by WildDog7000** [ellunium/sketch-measure-latest#17]
macOS Catalina v10.15.6
Sketch v69

Get stuck at the beginning
<img width="306" alt="截屏2020-10-09 下午3 26 54" src="https://user-images.githubusercontent.com/29428191/95555190-fd148880-0a43-11eb-99c4-7525a3c40083.png">

This version is only one We have，  can display font and color style name。

Guessing ...Maybe it's color names conflict with v69 new Color Variables feature？

**Comment by ellunium** [comment]
It should be working now.

[Give it a try and let me know.](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)

**Comment by WildDog7000** [comment]
> It should be working now.
> 
> [Give it a try and let me know.](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)

It's working now ! Thanks a looooot !
