### ISSUE TITLE
Problem: Sketch v53.2 crashes on plugin open

### ISSUE THREAD

**Issue by mattiacorci** [ellunium/sketch-measure-latest#2]
I'm getting serious problem trying to use this plugin with Sketch v53.2.
Every time I enable the plugin and I try to open plugin settings or it's toolbar, Sketch closes unexpectedly.

Is Sketch 53.2 handled and it should works? Or there is an internal log file? I could help fix the issue..

I've already tried to uninstall/reinstall but still getting the same problem.

here there are some error data displayed.
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000068
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Performing @selector(runPlugin:) from sender NSMenuItem 0x600009b2fde0
```

**Comment by ellunium** [comment]
@mattiacorci:
- Which OS do you have on your mac? Mojave? High Sierra
- Do you have Sketch Measure 2.8.0?
- Could you provide me with a sample file that I can reproduce the problem?

Sketch v53.2 (72643) is actually needed to make sure this fork (sketch-measure-latest v2.8.0) works properly.

# Log files
>Or there is an internal log file? I could help fix the issue.

You can try to get the output of the Plugin Log:

> 1.	Open Utilities > Console.app
> 2.	Expand ~/Library/Logs in the left window, and select com.bohemiancoding.sketch3
> 3.	In the right window, select the file called Plugin Log.log. If this file doesn't exist, you need to get the plugin (or any plugin for that matter) to crash or to run, then the file will be created. Select the contents of the log.
> 4.	If you can reproduce the crash consistently, you can select the file called Plugin Log.log and select Clear in the action menu first. Run the plugin again, and only the crash information relevant to the plugin in that moment will appear. Select the contents of the log.
> 5.	Copy/paste the output here


# Did you try this first?

Remember to **uninstall the plugin**, **restart sketch** and install the downloaded version, just to make sure there's **no cached plugin information**.

Also, make sure you're using **Sketch v53.2 (72643)**.

### Get the Fork version (v2.8.0)
**[Download from sketch-measure-latest](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)**

# Still not working?
Follow the steps below:

- [ ] Uninstall the plugin
- [ ] Quit Sketch
- [ ] Follow the steps bellow to remove the `PluginsWarehouse` folder
- [ ] [Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure-latest/archive/master.zip)
- [ ] Reinstall the plugin
- [ ] Test the `Mark Properties / Spec Export` again

> Remove the `PluginsWarehouse` folder that lives in `~/Library/Application Support/com.bohemiancoding.sketch3/`. This is where we cache plugin downloads, and if you’ve been testing different versions of your appcast, you probably have some old stuff there that’s worth cleaning.
> - Go to the Finder of Mac OS
> - From the “Go” menu navigate down to “Go to Folder” or...
> - Hit Command+Shift+G from the Mac OS X desktop or a Finder window
> - Paste the folder location `~/Library/Application Support/com.bohemiancoding.sketch3/`
> - Remove/Delete the `PluginsWarehouse` folder



Let know how it goes :)

**Comment by mattiacorci** [comment]
@ellunium thanks for your support. 
Following your steps the plugin correctly works without crashing Sketch! 
FYI I was using Mojave, with Sketch Measure 2.8.0 and the problem happened with a simple dartboard with a rectangle in it. But now it's magically working :)

Thanks
