### ISSUE TITLE
Minor - Wrong link in description

### ISSUE THREAD

**Issue by Jacxz** [ellunium/sketch-measure-latest#3]
In the first part of the description you're linking to the standard plugin, not "sketch-measure-latest".
So upon downloading I didn't get the 2.8.0 release as expected ;)

_Remember to uninstall current plugin version, restart sketch then, install the new version.
Download the latest zip file from the fork
Check the version of the installed plugin:
...
It should say 2.8.0_

->
replace https://github.com/ellunium/sketch-measure/archive/master.zip
with **https://github.com/ellunium/sketch-measure-latest/archive/master.zip**

**Comment by ellunium** [comment]
Nice catch @Jacxz ! Thanks!
