### ISSUE TITLE
Feature request : export for both color. dimension type ?

### ISSUE THREAD

**Issue by Raghav789** [ellunium/sketch-measure-latest#4]
Most of the project I work on is for both iOS/Android platform so is it possible to have both values listed in the sketch export HTML file? some sort of global dropdown would be fine or just for each property like for example, color value can be interchanged in the inspector.

**Comment by ellunium** [comment]
Hi @Raghav789, could you please illustrate what you're talking about with couple screenshots?
Also, did you know that you can tap on the color to get extra values?

![colors](https://user-images.githubusercontent.com/34353493/54835850-461ab580-4cc3-11e9-9a2c-ffab42c58edb.gif)

**Comment by Raghav789** [comment]
wow cool, I didn't no that in the setting we can select only one measurement and color, I thought there will be only one.
thank an you so much
