### ISSUE TITLE
Exported HTML breakes up text bounding boxes, displays different fonts

### ISSUE THREAD

**Issue by buonjornoo** [ellunium/sketch-measure-latest#5]
Exported *index.html* breaks um a text in separate bounding boxes. Characters like **ä**, **ü** and **ö** are displayed in another font. In my case it was supposed to be Frutiger but is now Lucida Grande. Additionally the index.html does not display the used Sketch-textstyles correctly/at all.
**Sketch Version 55.1**
**Browsers**: Chrome, Firefox, Safari
**MacOS** Version 10.13.6 (17G7024)

**Comment by Jasper324** [comment]
After export   html , it still cannot be recognized

**Comment by ellunium** [comment]
That’s a foundation problem that I don’t plan to fix. The plugin since it was created didn’t support multiple styles and font sizes within the same text box, I have no plans to introduce the features, maybe Utom will on the original plugin.
