### ISSUE TITLE
Wrong group size 

### ISSUE THREAD

**Issue by psnewman** [ellunium/sketch-measure-latest#7]
Plugin creates a group of layers with bounding box offset and it makes hard selecting this group on the canvas directly. This issue could be solved by selecting any layer of this group and hit Esc but it would be great to have normal bounding box from the start. Thanks!

![image](https://user-images.githubusercontent.com/20703766/60508854-3c4a1a80-9cd4-11e9-9155-02097e2671de.png)

**Comment by ellunium** [comment]
@pashka87 

This should have been fixed with this fork.
Give this a try: https://github.com/ellunium/sketch-measure-latest#still-not-working

Let me know if you still have this problem.
Also, try turning off all your plugins and running only Measure to see how it goes.
Might be a conflict.
