### ISSUE TITLE
beta tool bar creates large box outline

### ISSUE THREAD

**Issue by createconsume** [ellunium/sketch-measure-latest#8]
Obviously the toolbar is still in beta but I def prefer this panel to the default.
<img width="202" alt="Screen Shot 2019-07-11 at 12 29 47 PM" src="https://user-images.githubusercontent.com/25509342/61068439-0691e980-a3d8-11e9-8891-9e73b913b284.png">

**Comment by Jeason0228** [comment]
maybe you can use without "beta" version...
i found this problem when i use plugin "Anima tool kits" stacks .

**Comment by ellunium** [comment]
@createconsume https://github.com/ellunium/sketch-measure-latest#a-note-on-toolbar-20-beta
