### ISSUE TITLE
Does this work for Sketch 56.2? What's the suggested version?

### ISSUE THREAD

**Issue by siddharthksuri** [ellunium/sketch-measure-latest#9]
@ellunium 
What's the newest version of Sketch where this plugin works in a stable & predictable manner?

I've been on Sketch 52.6 for a while now, due to limited plugin support. Export functionality is more crucial than anything else.

I would appreciate input from anyone else who is using it as well.

Thanks!

**Comment by ellunium** [comment]
@siddharthksuri this fork should work on all versions past 52+
I’m on vacation now, but last week it was working with the latest up until then.

What’s not working for you? What are you trying to do and how?

**Comment by siddharthksuri** [comment]
Thanks! I appreciate the response.
I tested it with some of my bulky design files & it appears to be working fine.

I wanted to make sure, since once a Sketch file is edited in 56, it will no longer work in 52.
